{{- range $index, $name := .Values.names }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .prefix }}-{{ .name }}-{{ .suffix }}"
data:
  name: "{{ .prefix }}-{{ .name }}-{{ .suffix }}"
---
{{- end }}