{{- range $index, $name := .Values.names }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ $.Values.prefix }}-{{ $name }}-{{ $.Values.suffix }}"
data:
  name: "{{ $.Values.prefix }}-{{ $name }}-{{ $.Values.suffix }}"
---
{{- end }}